### ISSUE TITLE
Scrape together a set of movie and TV show quotes

### ISSUE THREAD

**Issue by NimaBoscarino** [alumni-lab/quote-chat#3]
- could be done by parsing a big corpus of scripts and splitting into sentences?
- look for existing databases?

**Comment by DraconianLore** [comment]
- https://www.filmsite.org/greatfilmquotes.html
- https://github.com/vilaboim/movie-quotes/blob/HEAD/movie-quotes.json
- http://forums.markzdanielewski.com/forum/other-stuff/out-of-the-way/3549-1-000-favourite-movie-quotes
- https://en.wikiquote.org/wiki/List_of_films
- https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html
- http://www.quodb.com/
- https://www.moviequotedb.com/

**Comment by DraconianLore** [comment]
we can also get a FREE Developer API key for MovieQuotes API
along with a ruby gem to access it
https://github.com/juanroldan1989/movie_quotes

**Comment by DraconianLore** [comment]
have downloaded scripts for the movies listed here....
[movie-list.txt](https://github.com/alumni-lab/quote-chat/files/3503735/movie-list.txt)

**Comment by NimaBoscarino** [comment]
This is currently being worked on in a different repository as it's own project: https://github.com/alumni-lab/script-db

When the scraper is in a working state (i.e. one movie with many characters + quotes), then we can use the scraper to populate this project's database, which our Express server will interact with.

**Comment by NimaBoscarino** [comment]
The scraper is in a working state, so it has been integrated into the project. The scraper could definitely use a little bit of work, though! E.g. we need to clean our data set a bit better, and expand beyond _just_ Lord of the Rings
